# Generated by Django 3.0.5 on 2021-05-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_auto_20210529_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='taputype',
        ),
        migrations.AddField(
            model_name='product',
            name='yapiDurumu',
            field=models.CharField(db_index=True, default='Yapı Durumu', max_length=200, verbose_name='Yapı Durumu'),
        ),
    ]
