# Generated by Django 3.0.5 on 2021-05-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_auto_20210530_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kredi_en',
            field=models.CharField(db_index=True, default='Kredi Uygunluk', max_length=200, null=True, verbose_name='Kredi'),
        ),
        migrations.AddField(
            model_name='product',
            name='kredi_tr',
            field=models.CharField(db_index=True, default='Kredi Uygunluk', max_length=200, null=True, verbose_name='Kredi'),
        ),
        migrations.AddField(
            model_name='product',
            name='yapiDurumu_en',
            field=models.CharField(db_index=True, default='Yapı Durumu', max_length=200, null=True, verbose_name='Yapı Durumu'),
        ),
        migrations.AddField(
            model_name='product',
            name='yapiDurumu_tr',
            field=models.CharField(db_index=True, default='Yapı Durumu', max_length=200, null=True, verbose_name='Yapı Durumu'),
        ),
    ]
