# Generated by Django 3.0.5 on 2021-05-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0004_auto_20210509_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
