# Generated by Django 3.0.5 on 2021-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0007_auto_20210509_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.ManyToManyField(blank=True, default=None, related_name='Available', to='real.Available'),
        ),
    ]
