# Generated by Django 3.0.5 on 2021-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0008_auto_20210509_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adress',
            field=models.CharField(db_index=True, default='Proje Adresi', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='garage',
            field=models.CharField(db_index=True, default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='m2',
            field=models.CharField(db_index=True, default='Metre Kare', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(db_index=True, default='Fiyatı', max_length=200),
        ),
    ]
