# Generated by Django 3.0.5 on 2021-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0010_auto_20210514_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shower',
            field=models.CharField(db_index=True, default='3', max_length=200),
        ),
    ]
