# Generated by Django 3.0.5 on 2021-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0012_auto_20210514_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='product',
            name='manager',
            field=models.CharField(db_index=True, default='Yönetici', max_length=200),
        ),
    ]
