# Generated by Django 3.0.5 on 2021-05-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0013_auto_20210514_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='position',
            field=models.CharField(choices=[('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('5+1', '5+1'), ('6+1', '6+1'), ('6+2', '6+2')], default='1+1', max_length=20),
        ),
    ]
