# Generated by Django 3.0.5 on 2021-05-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0016_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
