# Generated by Django 3.0.5 on 2021-05-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0017_agent_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
