# Generated by Django 3.0.5 on 2021-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Ürün Aaçıklama 263 Ten az 263 çok olmuyacak', max_length=263),
        ),
    ]
