# Generated by Django 3.0.5 on 2021-05-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0020_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='bedroom',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='managername',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='yearofproduction',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
    ]
