# Generated by Django 3.0.5 on 2021-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0021_auto_20210518_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='managername',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
    ]
