# Generated by Django 3.0.5 on 2021-05-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0022_auto_20210518_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
    ]
