# Generated by Django 3.0.5 on 2021-05-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0023_agent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
