# Generated by Django 3.0.5 on 2021-05-18 19:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0024_agent_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
