# Generated by Django 3.0.5 on 2021-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0025_auto_20210518_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
