# Generated by Django 3.0.5 on 2021-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0027_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='center',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='highway',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='hospital',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='scholl',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sea',
            field=models.CharField(db_index=True, default='İnformation', max_length=200),
        ),
    ]
