# Generated by Django 3.0.5 on 2021-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0031_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plans',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
    ]
