# Generated by Django 3.0.5 on 2021-05-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0036_auto_20210523_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='durum',
            field=models.CharField(db_index=True, default='Durum', max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, default='Şehit', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='position',
            field=models.CharField(db_index=True, default='Oda Türü', max_length=200),
        ),
    ]
