# Generated by Django 3.0.5 on 2021-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0037_auto_20210529_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, default='Şehir', max_length=200),
        ),
    ]
