# Generated by Django 3.0.5 on 2021-05-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0041_auto_20210530_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='durum_en',
        ),
        migrations.RemoveField(
            model_name='available',
            name='durum_tr',
        ),
    ]
