# Generated by Django 3.0.5 on 2021-05-30 10:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_auto_20210529_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, default='Proje İsmi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(db_index=True, default='Proje İsmi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='position_en',
            field=models.CharField(db_index=True, default='Oda Türü', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='position_tr',
            field=models.CharField(db_index=True, default='Oda Türü', max_length=200, null=True),
        ),
    ]
