# Generated by Django 3.0.5 on 2021-05-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_auto_20210530_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imar_en',
            field=models.CharField(db_index=True, default='İnformation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imar_tr',
            field=models.CharField(db_index=True, default='İnformation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='su_en',
            field=models.CharField(db_index=True, default='Su', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='su_tr',
            field=models.CharField(db_index=True, default='Su', max_length=200, null=True),
        ),
    ]
