# Generated by Django 3.0.5 on 2021-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_auto_20210530_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
