# Generated by Django 3.0.5 on 2021-05-29 15:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(db_index=True, default='Durum', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Şehir', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(db_index=True, default='Oda Türü', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, default='Proje İsmi', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('adress', models.CharField(db_index=True, default='Proje Adresi', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('manager', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('managername', models.CharField(db_index=True, default='İnformation', max_length=200)),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('plans', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('price', models.CharField(db_index=True, default='Fiyatı', max_length=200)),
                ('m2', models.CharField(db_index=True, default='m2', max_length=200)),
                ('room', models.CharField(db_index=True, default='m2', max_length=200, verbose_name='Bölüm & Oda')),
                ('aidat', models.CharField(db_index=True, default='Aidat', max_length=200, verbose_name='Aidat')),
                ('isitma', models.CharField(db_index=True, default='Isıtma', max_length=200, verbose_name='Isıtma')),
                ('yas', models.CharField(db_index=True, default='Bina Yaşı', max_length=200, verbose_name='Bina Yaşı')),
                ('kredi', models.CharField(db_index=True, default='Kredi', max_length=200, verbose_name='Kredi Uygunluk')),
                ('durum', models.CharField(db_index=True, default='Durum', max_length=200, verbose_name='Durum')),
                ('takaslı', models.CharField(db_index=True, default='Takaslı', max_length=200, verbose_name='Takaslı')),
                ('kullanimAmaci', models.CharField(db_index=True, default='Takaslı', max_length=200, verbose_name='Kullanım Amacı')),
                ('airport', models.CharField(db_index=True, default='Hava Alanına Uzaklık', max_length=200)),
                ('anayol', models.CharField(db_index=True, default='Anayola Uzaklık', max_length=200)),
                ('center', models.CharField(db_index=True, default='Merkeze Uzaklık', max_length=200)),
                ('sea', models.CharField(db_index=True, default='Denize Uzaklık', max_length=200)),
                ('taputype', models.CharField(db_index=True, default='Tapu Durumu', max_length=200)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('available', models.ManyToManyField(blank=True, default=None, related_name='Available', to='workplace.Available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='workplace.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='City', to='workplace.City')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.Product')),
            ],
        ),
    ]
