# Generated by Django 3.0.5 on 2021-05-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='City', to='workplace.Room'),
        ),
    ]
