# Generated by Django 3.0.5 on 2021-05-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0003_auto_20210529_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.CharField(db_index=True, default='m2', max_length=200, verbose_name='Bölüm & Oda'),
        ),
    ]
