# Generated by Django 3.0.5 on 2021-05-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0005_auto_20210530_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=21, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
